
import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";

const InriaSans = Inria_Sans({
  weight: ["300", "400", "700"],
  variable: "--font-inria-sans",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking-system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InriaSans.variable} antialiased`}>
      <StoreProvider>
        <div id="root">{children}</div>
      </StoreProvider>
      </body>
    </html>
  );
}
